CREATE DATABASE dbFiliadoPTC
GO

USE dbFiliadoPTC
GO

CREATE TABLE tbFiliado(
	numInscricao INT PRIMARY KEY IDENTITY(1,1)
	,nomeFiliado NVARCHAR(300) NOT NULL
	,siglaPartido NVARCHAR(10) NOT NULL
	,nomePartido NVARCHAR(300) NOT NULL
	,codMunicipio INT NOT NULL
	,nomeMunicipio NVARCHAR(300) NOT NULL
	,zonaEleitoral INT NOT NULL
	,dataFiliacao DATE NOT NULL
	,situacaoRegistro NVARCHAR(100) NOT NULL
)
GO

INSERT INTO tbFiliado(nomeFiliado, siglaPartido, nomePartido, codMunicipio, nomeMunicipio, zonaEleitoral, dataFiliacao, situacaoRegistro) VALUES
('JORGE LUIS FERREIRA DOS SANTOS','PTC','PARTIDO TRABALHISTA CRISTÃO',37516,'NAZARÉ',30,'1989-06-02','REGULAR')
,('BENTA XAVIER RODRIGUES','PTC','PARTIDO TRABALHISTA CRISTÃO',39659,'VITÓRIA DA CONQUISTA',41,'1990-05-11','REGULAR')
,('NOE LEITE DA SILVA','PTC','PARTIDO TRABALHISTA CRISTÃO',33359,'ANTÔNIO GONÇALVES',53,'2003-09-26','REGULAR')
,('ELIEL ALMEIDA SILVA','PTC','PARTIDO TRABALHISTA CRISTÃO',36854,'LAURO DE FREITAS',180,'2011-04-08','DESFILIADO')
,('ALINE DE SOUZA','PTC','PARTIDO TRABALHISTA CRISTÃO',34690,'CONCEIÇÃO DO JACUÍPE',192,'2003-09-30','REGULAR')
,('MARIA HELENA GOMES','PTC','PARTIDO TRABALHISTA CRISTÃO',38539,'SANTA BRÍGIDA',181,'2003-08-11','REGULAR')
,('PEDRO FERNANDO GONCALVES','PTC','PARTIDO TRABALHISTA CRISTÃO',35076,'ENCRUZILHADA',152,'2003-08-20','REGULAR')
,('FABIO LUIS OLIVEIRA DA CRUZ','PTC','PARTIDO TRABALHISTA CRISTÃO',38792,'SÃO FÉLIX',118,'2016-03-30','REGULAR')
,('JOAQUIM GOMES DA SILVA','PTC','PARTIDO TRABALHISTA CRISTÃO',38679,'SANTANÓPOLIS',74,'2011-10-07','REGULAR')
,('TIAGO JOSE DOS SANTOS BARBOSA','PTC','PARTIDO TRABALHISTA CRISTÃO',38490,'SALVADOR',10,'2003-09-22','REGULAR')
,('IONE PARAISO DOS SANTOS','PTC','PARTIDO TRABALHISTA CRISTÃO',36471,'ITUBERÁ',32,'2015-09-29','REGULAR')
,('JOSE FELIX DE SOUZA','PTC','PARTIDO TRABALHISTA CRISTÃO',30996,'JOÃO DOURADO',199,'1995-12-04','REGULAR')
,('JURACY DE MAGALHAES FERREIRA','PTC','PARTIDO TRABALHISTA CRISTÃO',36854,'LAURO DE FREITAS',180,'2003-02-10','REGULAR')
,('NADIA PINHEIRO TRINDADE OLIVEIRA','PTC','PARTIDO TRABALHISTA CRISTÃO',30058,'EUNÁPOLIS',203,'1996-01-26','REGULAR')
,('JOSE ANTONIO DO NASCIMENTO ALVES DE OLIVEIRA','PTC','PARTIDO TRABALHISTA CRISTÃO',38539,'SANTA BRÍGIDA',181,'2016-03-31','REGULAR')
,('NILSOMAR GONCALVES DE SOUZA','PTC','PARTIDO TRABALHISTA CRISTÃO',33278,'ANGICAL',126,'2007-10-04','REGULAR')
,('MANOEL DIAS ROCHA','PTC','PARTIDO TRABALHISTA CRISTÃO',33138,'ALAGOINHAS',163,'2010-02-21','REGULAR')
,('ANTONIO MARCOS SILVA SANTOS','PTC','PARTIDO TRABALHISTA CRISTÃO',38733,'SANTO ANTÔNIO DE JESUS',202,'1989-04-25','REGULAR')
,('JANDIRA SOUZA SANTA LUZIA CARMO','PTC','PARTIDO TRABALHISTA CRISTÃO',39632,'VERA CRUZ',141,'1999-09-30','REGULAR')
,('JEDIVAL RIBEIRO SANTOS','PTC','PARTIDO TRABALHISTA CRISTÃO',35750,'INHAMBUPE',44,'2011-09-29','REGULAR')
,('JOÃO SEBASTIÃO SOUZA MOURA DE ALMEIDA','PTC','PARTIDO TRABALHISTA CRISTÃO',38490,'SALVADOR',1,'2003-09-26','REGULAR')
,('ANTÔNIO JOSÉ DOS SANTOS','PTC','PARTIDO TRABALHISTA CRISTÃO',35971,'ITABUNA',28,'1996-05-24','REGULAR')
,('JOSIENE ANDRADE DE SOUZA','PTC','PARTIDO TRABALHISTA CRISTÃO',39870,'SANTA LUZIA',133,'2020-04-04','SUB_JUDICE')
GO

SELECT * FROM tbFiliado WHERE nomeFiliado LIKE 'ANTONIO%' /*AND nomeFiliado LIKE 'ANTÔNIO'*/
GO

SELECT * FROM tbFiliado WHERE nomeFiliado LIKE '% SEBASTIÃO%'
GO

SELECT * FROM tbFiliado WHERE nomeFiliado LIKE '%OS'
GO

SELECT nomeFiliado AS 'Nome do Filiado' FROM tbFiliado WHERE nomeMunicipio LIKE 'São Félix'
GO

SELECT nomeFiliado AS 'Nome do Filiado' FROM tbFiliado WHERE nomeMunicipio LIKE 'Inhambupe'
GO

SELECT nomeMunicipio AS 'Nome do Municipio' FROM tbFiliado WHERE nomeMunicipio LIKE 'Santa %' GROUP BY nomeMunicipio
GO

SELECT nomeMunicipio AS 'Nome do Municipio' FROM tbFiliado WHERE nomeMunicipio LIKE 'E%' GROUP BY nomeMunicipio
GO

SELECT nomeMunicipio AS 'Nome do Municipio' FROM tbFiliado WHERE nomeMunicipio LIKE '% CRUZ%' OR nomeMunicipio LIKE '%CRUZ %' GROUP BY nomeMunicipio
GO

SELECT nomeMunicipio AS 'Nome do Municipio' FROM tbFiliado WHERE nomeMunicipio LIKE '% CRUZ%' OR nomeMunicipio LIKE '%CRUZ %' GROUP BY nomeMunicipio
GO

SELECT nomeMunicipio AS 'Nome do Municipio' FROM tbFiliado WHERE nomeMunicipio LIKE '% de %' GROUP BY nomeMunicipio
GO

SELECT * FROM tbFiliado WHERE dataFiliacao BETWEEN '1990-01-01' AND '2000-01-01'
GO

SELECT * FROM tbFiliado WHERE dataFiliacao BETWEEN '2010-01-02' AND '2010-03-01'
GO

SELECT * FROM tbFiliado WHERE dataFiliacao BETWEEN '2007-06-01' AND '2007-12-31'
GO

SELECT * FROM tbFiliado WHERE situacaoRegistro LIKE 'REGULAR'
GO

SELECT * FROM tbFiliado WHERE zonaEleitoral=203
GO

SELECT * FROM tbFiliado WHERE zonaEleitoral=180
GO

SELECT * FROM tbFiliado WHERE zonaEleitoral=199
GO

SELECT MAX(zonaEleitoral) AS 'Zona Eleitoral de Maior Número' FROM tbFiliado
GO

SELECT MIN(zonaEleitoral) AS 'Zona Eleitoral de Menor Número' FROM tbFiliado
GO

UPDATE tbFiliado SET siglaPartido = 'PT' WHERE codMunicipio = 36471
GO

UPDATE tbFiliado SET siglaPartido = 'PMDB' WHERE codMunicipio = 38490
GO

UPDATE tbFiliado SET siglaPartido = 'PC' WHERE nomeMunicipio LIKE 'SANTANÓPOLIS'
GO

UPDATE tbFiliado SET siglaPartido = 'PC' WHERE nomeMunicipio LIKE 'SANTANÓPOLIS'
GO

UPDATE tbFiliado SET siglaPartido = 'PV' AND nomePartido = 'Partido Verde' WHERE nomeMunicipio LIKE 'SÃO FÉLIX'
GO

UPDATE tbFiliado SET siglaPartido = 'PSDB' AND nomePartido = 'Partido da Social Democracia Brasileira' WHERE nomeMunicipio LIKE 'ENCRUZILHADA'
GO

UPDATE tbFiliado SET nomeFiliado = 'JORGE LUIS MAGALHÃES DOS SANTOS' WHERE nomeFiliado LIKE 'JORGE LUIS FERREIRA DOS SANTOS'
GO

UPDATE tbFiliado SET nomeFiliado = 'RENATA XAVIER RODRIGUES' WHERE nomeFiliado LIKE 'BENTA XAVIER RODRIGUES'
GO

UPDATE tbFiliado SET nomeFiliado = 'NOEL LEITE DA SILVA' WHERE nomeFiliado LIKE 'NOE LEITE DA SILVA'
GO

UPDATE tbFiliado SET nomeFiliado = 'NOEL LEITE DA SILVA' WHERE nomeFiliado LIKE 'NOE LEITE DA SILVA'
GO

UPDATE tbFiliado SET situacaoRegistro = 'REGULAR' WHERE nomeFiliado LIKE 'JOSIENE ANDRADE DE SOUZA'
GO

UPDATE tbFiliado SET situacaoRegistro = 'REGULAR' WHERE nomeFiliado LIKE 'ELIEL ALMEIDA SILVA'
GO

UPDATE tbFiliado SET situacaoRegistro = 'DESFILIADO' WHERE nomeFiliado LIKE 'ALINE DE SOUZA'
GO

SELECT * FROM tbFiliado
ALTER TABLE tbFiliado ADD sexoFiliado CHAR(1) NULL
SELECT * FROM tbFiliado